### PR TITLE
*: check cq before starting call op

### LINKED ISSUE #118: Tests and benchmarks failed after upgrade gRPC to 1.7.2
As described in https://github.com/pingcap/grpc-rs/pull/113#issuecomment-344896176, benchmarks failed. 
And unit tests fail frequently because of `call.c:2032] assertion failed: grpc_cq_begin_op(call->cq, notify_tag)`

For the benchmark, it looks like client and server failed to send the last message and close the connection, detailed logs:

Client:
```
Nov 18 14:34:27.584 INFO listening on [::]:10110
Nov 18 14:34:27.703 INFO receive client setup: server_targets: "localhost:33821" client_type: ASYNC_CLIENT security_params {use_test_ca: true server_host_override: "foo.test.google.fr"} outstanding_rpcs_per_channel: 100 client_channels: 64 rpc_type: STREAMING load_params {closed_loop {}} payload_config {simple_params {}} histogram_params {resolution: 0.01 max_possible: 60000000000} channel_args {name: "grpc.optimization_target" str_value: "throughput"}
Nov 18 14:34:27.859 INFO receive client mark: reset: true
Nov 18 14:34:32.864 INFO receive client mark: reset: true
Nov 18 14:35:02.862 INFO receive client mark: reset: true
```
 
Server:
```
Nov 18 14:34:27.581 INFO listening on [::]:10100
Nov 18 14:34:27.594 INFO receive server setup: server_type: ASYNC_SERVER security_params {use_test_ca: true server_host_override: "foo.test.google.fr"} channel_args {name: "grpc.optimization_target" str_value: "throughput"}
Nov 18 14:34:32.865 INFO receive server mark: reset: true
```

They are both missing a log for shutting down.
https://github.com/pingcap/grpc-rs/blob/e45a84332e7e8c5e490ade91a501610f612fdce8/benchmark/src/worker.rs#L113
https://github.com/pingcap/grpc-rs/blob/e45a84332e7e8c5e490ade91a501610f612fdce8/benchmark/src/worker.rs#L77

CC #107

### PR DESCRIPTION
**Pull request by BusyJay**
Add a ref count to trace the completion queue lifetime, so avoid the race condition between shutdown queue and starting call operation.

close #118.

### CODE REVIEW

File: grpc-sys/build.rs [hunk 1]
```diff
@@ -27,7 +27,10 @@ use pkg_config::Config as PkgConfig;
 const GRPC_VERSION: &'static str = "1.6.1";
 
 fn link_grpc(cc: &mut Build, library: &str) {
-    match PkgConfig::new().atleast_version(GRPC_VERSION).probe(library) {
+    match PkgConfig::new()
```
Comment (overvenus) [inline grpc-sys/build.rs]: Is it an unrelated change?

**Comment by disksing** [comment]
PTAL @AndreMouche

File: src/cq.rs [hunk 2]
```diff
@@ -65,18 +123,17 @@ impl CompletionQueue {
...
     /// `Event::QueueShutdown` events only.
     pub fn shutdown(&self) {
-        unsafe {
-            grpc_sys::grpc_completion_queue_shutdown(self.handle.cq);
-        }
-    }
-
-    pub fn as_ptr(&self) -> *mut GrpcCompletionQueue {
-        self.handle.cq
+        self.handle.unref()
```
Comment (overvenus) [inline src/cq.rs]: How about adding a flag so that CQ will not accept any new requests.

File: src/cq.rs [hunk 3]
```diff
@@ -43,6 +85,22 @@ impl Drop for CompletionQueueHandle {
     }
 }
 
+pub struct CompletionQueueRef<'a> {
+    queue: &'a CompletionQueue,
+}
+
+impl<'a> CompletionQueueRef<'a> {
+    pub fn as_ptr(&self) -> *mut GrpcCompletionQueue {
```
Comment (overvenus) [inline src/cq.rs]: The `ptr` may still outlive `CompletionQueueRef`.

File: src/cq.rs (hunk 2 above)
Comment (BusyJay) [reply src/cq.rs]: `ref_cnt` ensures that already.

File: src/cq.rs (hunk 3 above)
Comment (BusyJay) [reply src/cq.rs]: Yes. Because there is no way to trace the lifetime of a raw pointer, so I guess that's the best guarantee we can get. Just like `Vec::as_ptr` can't provide any promise of lifetime of the returned value. `CompletionQueueRef` here just ensures the completion queue will not be shutdown when ref is still valid.

**Comment by BusyJay** [comment]
ping

File: src/cq.rs [hunk 4]
```diff
@@ -33,6 +41,65 @@ impl CompletionQueueHandle {
     pub fn new() -> CompletionQueueHandle {
         CompletionQueueHandle {
             cq: unsafe { grpc_sys::grpc_completion_queue_create_for_next(ptr::null_mut()) },
+            ref_cnt: AtomicIsize::new(1),
+        }
+    }
+
+    fn add_ref(&self) -> Result<()> {
+        loop {
```
Comment (siddontang) [inline src/cq.rs]: why not using SpinLock to simplify the code?

Comment (BusyJay) [reply src/cq.rs]: I don't think use `SpinLock` is appropriate. Just like we won't use `SpinLock<T>` to replace `AtomicT`, because `AtomicT` is exactly what we want.

File: src/cq.rs [hunk 5]
```diff
@@ -33,6 +41,65 @@ impl CompletionQueueHandle {
...
+            {
+                return Ok(());
+            }
+        }
+    }
+
+    fn unref(&self) {
+        let shutdown = loop {
+            let cnt = self.ref_cnt.load(Ordering::SeqCst);
+            if cnt == 0 {
```
Comment (siddontang) [inline src/cq.rs]: can cnt < 0?

File: src/cq.rs [hunk 6]
```diff
@@ -33,6 +41,65 @@ impl CompletionQueueHandle {
...
+                return;
+            }
+            let new_cnt = cnt - cnt.signum();
```
Comment (siddontang) [inline src/cq.rs]: if cnt is -1, new cnt is 0?

Comment (BusyJay) [reply src/cq.rs]: Yes.

Comment (siddontang) [reply src/cq.rs]: can you explain why we need to handle negative here? can we break the loop until the cnt is -1?

Comment (BusyJay) [reply src/cq.rs]: I think this is explained in https://github.com/pingcap/grpc-rs/pull/125/files#diff-c555e9a56a6bc20f38bbef46ccdd1efbR30.

Comment (siddontang) [reply src/cq.rs]: IMO here `cnt - cnt.signum` and later `-cnt + 1` in the shutdown confuse me, and I think it is hard to understand them easily at first glance. 
Why not using a SpinLock to control the reference counter and shutdown, or using two atomic value for counter and shutdown.

Comment (BusyJay) [reply src/cq.rs]: As I said in https://github.com/pingcap/grpc-rs/pull/125#discussion_r155700879, `SpinLock` is not appropriate here. The usages of atomic value here are just very basic. They are just like `fetch_add` or any other encapsulated functions except that they don't get fancy names.

Only using one atomic value here to get better performance and smaller struct size. And I think the code here is also very straightforward and also commented.

Comment (siddontang) [reply src/cq.rs]: As I said before, when I first see `cnt - cnt.signum()` and `-cnt + 1`, I have to think deeply what is the meaning of this, it is not straightforward. Can you add some comments?
